[0m12:45:17.281038 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E558B92390>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E55D7E8390>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E55D7E8650>]}


============================== 12:45:17.285052 | 0122d5a0-56e7-4782-817d-b0c71c9b79ed ==============================
[0m12:45:17.285052 [info ] [MainThread]: Running with dbt=1.10.4
[0m12:45:17.285052 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\niv22\\.dbt', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'invocation_command': 'dbt init DBT_Init_1', 'introspect': 'True', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m12:45:17.303627 [debug] [MainThread]: Starter project path: C:\Users\niv22\AppData\Local\Programs\Python\Python311\Lib\site-packages\dbt\include\starter_project
[0m12:45:17.338627 [info ] [MainThread]: 
Your new dbt project "DBT_Init_1" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m12:45:17.338627 [info ] [MainThread]: Setting up your profile.
[0m12:47:02.551635 [info ] [MainThread]: Profile DBT_Init_1 written to C:\Users\niv22\.dbt\profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m12:47:02.554642 [debug] [MainThread]: Command `dbt init` succeeded at 12:47:02.554642 after 105.34 seconds
[0m12:47:02.556642 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E556BB8DD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E55A1DDD90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E55D7A5690>]}
[0m12:47:02.557641 [debug] [MainThread]: Flushing usage events
[0m12:47:03.356462 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m12:57:16.284583 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000209AF344F10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000209AF6C9C90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000209AF6CAD50>]}


============================== 12:57:16.287584 | e45539ab-d065-48c7-8df6-dad569b5a1f3 ==============================
[0m12:57:16.287584 [info ] [MainThread]: Running with dbt=1.10.4
[0m12:57:16.287584 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'fail_fast': 'False', 'profiles_dir': 'C:\\Users\\niv22\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'static_parser': 'True', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'target_path': 'None', 'invocation_command': 'dbt run', 'send_anonymous_usage_stats': 'True'}
[0m12:57:16.288589 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Project_CV\Projects\DBT_ProjectNum_1\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m12:57:16.288589 [debug] [MainThread]: Command `dbt run` failed at 12:57:16.288589 after 0.06 seconds
[0m12:57:16.289588 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000209AF6C9450>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000209AF6CAE90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000209A8CE0A50>]}
[0m12:57:16.289588 [debug] [MainThread]: Flushing usage events
[0m12:57:16.924879 [debug] [MainThread]: An error was encountered while trying to flush usage events
<<<<<<< HEAD
[0m14:39:16.652063 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B77225E310>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B77225D290>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B7722B8910>]}


============================== 14:39:16.655072 | 4888d161-be19-4e27-9fda-6847eab9a4cc ==============================
[0m14:39:16.655072 [info ] [MainThread]: Running with dbt=1.10.4
[0m14:39:16.655072 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\niv22\\.dbt', 'fail_fast': 'False', 'warn_error': 'None', 'log_path': 'logs', 'version_check': 'True', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'introspect': 'True', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'target_path': 'None', 'invocation_command': 'dbt list', 'send_anonymous_usage_stats': 'True'}
[0m14:39:16.656062 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Project_CV\Projects\DBT_ProjectNum_1\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m14:39:16.656062 [debug] [MainThread]: Command `dbt list` failed at 14:39:16.656062 after 0.05 seconds
[0m14:39:16.657064 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B7722D5210>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B7722D5310>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B77225F790>]}
[0m14:39:16.657064 [debug] [MainThread]: Flushing usage events
[0m14:39:18.179731 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m14:54:14.472251 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024E941DE250>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024E94216950>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024E93F9F390>]}


============================== 14:54:14.474252 | 02564fbc-dbd6-43ae-947f-b0c7198d49c4 ==============================
[0m14:54:14.474252 [info ] [MainThread]: Running with dbt=1.10.4
[0m14:54:14.475251 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'profiles_dir': 'C:\\Users\\niv22\\.dbt', 'log_path': 'logs', 'version_check': 'True', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'introspect': 'True', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'target_path': 'None', 'invocation_command': 'dbt list', 'send_anonymous_usage_stats': 'True'}
[0m14:54:14.475251 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Project_CV\Projects\DBT_ProjectNum_1\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m14:54:14.476251 [debug] [MainThread]: Command `dbt list` failed at 14:54:14.476251 after 0.05 seconds
[0m14:54:14.476251 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024E941D6910>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024E941DE410>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024E941DF990>]}
[0m14:54:14.477251 [debug] [MainThread]: Flushing usage events
[0m14:54:15.325192 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m20:26:49.741043 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000255E7372110>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000255EA9C7690>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000255EA72F0D0>]}


============================== 20:26:49.744042 | 6fdfe448-e5d6-4b58-bcf9-e0aef4de6f5a ==============================
[0m20:26:49.744042 [info ] [MainThread]: Running with dbt=1.10.4
[0m20:26:49.744042 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\niv22\\.dbt', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'introspect': 'True', 'target_path': 'None', 'invocation_command': 'dbt debug', 'send_anonymous_usage_stats': 'True'}
[0m20:26:49.755062 [info ] [MainThread]: dbt version: 1.10.4
[0m20:26:49.756244 [info ] [MainThread]: python version: 3.11.5
[0m20:26:49.756244 [info ] [MainThread]: python path: C:\Users\niv22\AppData\Local\Programs\Python\Python311\python.exe
[0m20:26:49.757244 [info ] [MainThread]: os info: Windows-10-10.0.26100-SP0
[0m20:26:49.794143 [info ] [MainThread]: Using profiles dir at C:\Users\niv22\.dbt
[0m20:26:49.795151 [info ] [MainThread]: Using profiles.yml file at C:\Users\niv22\.dbt\profiles.yml
[0m20:26:49.796203 [info ] [MainThread]: Using dbt_project.yml file at C:\Project_CV\Projects\DBT_ProjectNum_1\dbt_project.yml
[0m20:26:49.796203 [error] [MainThread]: Encountered an error:
Internal Error
  Profile should not be None if loading profile completed
[0m20:26:49.797203 [debug] [MainThread]: Command `dbt debug` failed at 20:26:49.797203 after 0.11 seconds
[0m20:26:49.797203 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000255EA9E5CD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000255EA96F750>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000255E7381990>]}
[0m20:26:49.798208 [debug] [MainThread]: Flushing usage events
[0m20:26:50.644040 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m15:57:25.433654 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000243C2F7C910>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000243C2FB5890>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000243C2F7FD10>]}


============================== 15:57:25.436662 | 65207a1b-b7d7-4252-99d1-9481fa2c3cd5 ==============================
[0m15:57:25.436662 [info ] [MainThread]: Running with dbt=1.10.4
[0m15:57:25.436662 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'profiles_dir': 'C:\\Users\\niv22\\.dbt', 'log_path': 'logs', 'debug': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'invocation_command': 'dbt run', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'static_parser': 'True', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m15:57:25.436662 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Project_CV\Projects\DBT_ProjectNum_1\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m15:57:25.437655 [debug] [MainThread]: Command `dbt run` failed at 15:57:25.437655 after 0.05 seconds
[0m15:57:25.437655 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000243C2FDB050>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000243C2D3C150>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000243C2D3F190>]}
[0m15:57:25.438654 [debug] [MainThread]: Flushing usage events
[0m15:57:26.082932 [debug] [MainThread]: An error was encountered while trying to flush usage events
=======
>>>>>>> 4f5bd49b70b832001883b7172dd14434b3db9324
[0m19:08:38.765531 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000211D3266410>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000211D2F2E610>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000211D32CEDD0>]}


============================== 19:08:38.769543 | 28f78784-0e78-46fe-986d-f8ccb59e23ab ==============================
[0m19:08:38.769543 [info ] [MainThread]: Running with dbt=1.10.4
[0m19:08:38.769543 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\niv22\\.dbt', 'fail_fast': 'False', 'warn_error': 'None', 'log_path': 'logs', 'version_check': 'True', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'invocation_command': 'dbt test', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m19:08:38.770544 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Project_CV\Projects\DBT_ProjectNum_1\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m19:08:38.770544 [debug] [MainThread]: Command `dbt test` failed at 19:08:38.770544 after 0.06 seconds
[0m19:08:38.771541 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000211CC8E0990>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000211D31B8210>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000211D32CC490>]}
[0m19:08:38.771541 [debug] [MainThread]: Flushing usage events
[0m19:08:39.768841 [debug] [MainThread]: An error was encountered while trying to flush usage events
